
package org.uoa.eolus;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "EolusService", targetNamespace = "http://eolus.uoa.org/", wsdlLocation = "http://n34.di.uoa.gr:8080/Madgik/Eolus?wsdl")
public class EolusService
    extends Service
{

    private final static URL EOLUSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.uoa.eolus.EolusService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.uoa.eolus.EolusService.class.getResource(".");
            url = new URL(baseUrl, "http://n34.di.uoa.gr:8080/Madgik/Eolus?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://n34.di.uoa.gr:8080/Madgik/Eolus?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EOLUSSERVICE_WSDL_LOCATION = url;
    }

    public EolusService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EolusService() {
        super(EOLUSSERVICE_WSDL_LOCATION, new QName("http://eolus.uoa.org/", "EolusService"));
    }

    /**
     * 
     * @return
     *     returns Eolus
     */
    @WebEndpoint(name = "EolusPort")
    public Eolus getEolusPort() {
        return super.getPort(new QName("http://eolus.uoa.org/", "EolusPort"), Eolus.class);
    }

}
