
package org.uoa.nefeli;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "NefeliService", targetNamespace = "http://nefeli.uoa.org/", wsdlLocation = "http://n18.di.uoa.gr:9998/Madgik/Nefeli?wsdl")
public class NefeliService
    extends Service
{

    private final static URL NEFELISERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.uoa.nefeli.NefeliService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.uoa.nefeli.NefeliService.class.getResource(".");
            url = new URL(baseUrl, "http://n18.di.uoa.gr:9998/Madgik/Nefeli?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://n18.di.uoa.gr:9998/Madgik/Nefeli?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        NEFELISERVICE_WSDL_LOCATION = url;
    }

    public NefeliService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NefeliService() {
        super(NEFELISERVICE_WSDL_LOCATION, new QName("http://nefeli.uoa.org/", "NefeliService"));
    }

    /**
     * 
     * @return
     *     returns Nefeli
     */
    @WebEndpoint(name = "NefeliPort")
    public Nefeli getNefeliPort() {
        return super.getPort(new QName("http://nefeli.uoa.org/", "NefeliPort"), Nefeli.class);
    }

}
